---

- name: configure CloudTrail in {{ trail_region }}
  cloudtrail:
    enable_log_file_validation: false
    include_global_events: '{{ (trail_region == aws_region) | bool }}'
    name: Default
    profile: '{{ aws_profile }}'
    region: '{{ trail_region }}'
    s3_bucket_name: '{{ aws_awslogs_bucket }}'
    state: enabled
  register: _aws_cloudtrail

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      configured CloudTrail in
      <a href="{{ _aws_cloudtrail_url }}?region={{ trail_region }}">{{
        trail_region }} in account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    _aws_cloudtrail is changed
