---

- name: set default region boolean fact
  set_fact:
    default_region: '{{ (trail_region == region) | bool }}'

- name: describe Default trail in {{ trail_region }}
  command: >
    aws cloudtrail describe-trails
                   --trail-name-list
                     'arn:aws:cloudtrail:{{
                        trail_region }}:{{ account }}:trail/Default'
                   --region '{{ trail_region }}'
                   --query 'trailList[0]'
                   --profile '{{ aws_profile }}'
  register: trails
  changed_when: False


- block:

  - name: set Default trail fact for {{ trail_region }}
    set_fact:
      default_trail: '{{ trails.stdout | from_json }}'

  - block:

    - name: update Default trail in {{ trail_region }}
      command: >
        aws cloudtrail update-trail
                       --name Default
                       --s3-bucket-name '{{ awslogs_bucket }}'
                       '{{ default_region
                           | ternary("--include-global-service-events",
                                     "--no-include-global-service-events") }}'
                       --enable-log-file-validation
                       --region '{{ trail_region }}'
                       --profile '{{ aws_profile }}'

    - name: call optional notifier
      include: 'roles/{{ notifier_role }}/tasks/main.yml'
      vars:
        message: >
          updated the Default trail in
          <a href="{{ cloudtrail_url }}?region={{ trail_region }}">{{
            trail_region }} in account {{ aws_profile }}</a>
      when: notifier_role is defined

    when: >
      default_trail.IncludeGlobalServiceEvents != default_region or
      default_trail.LogFileValidationEnabled   != True or
      default_trail.S3BucketName               != '{{ awslogs_bucket }}'

  when: trails.stdout != 'null'


- block:

  - name: create Default trail in {{ trail_region }}
    command: >
      aws cloudtrail create-trail
                     --name Default
                     --s3-bucket-name '{{ awslogs_bucket }}'
                     '{{ default_region
                         | ternary("--include-global-service-events",
                                   "--no-include-global-service-events") }}'
                     --enable-log-file-validation
                     --region '{{ trail_region }}'
                     --profile '{{ aws_profile }}'

  - name: call optional notifier
    include: 'roles/{{ notifier_role }}/tasks/main.yml'
    vars:
      message: >
        created the Default trail in
        <a href="{{ cloudtrail_url }}?region={{ trail_region }}">{{
          trail_region }} in account {{ aws_profile }}</a>
    when: notifier_role is defined

  when: trails.stdout == 'null'


- name: get Default trail status in {{ trail_region }}
  command: >
    aws cloudtrail get-trail-status
                   --name Default
                   --region '{{ trail_region }}'
                   --query 'IsLogging'
                   --profile '{{ aws_profile }}'
  register: is_logging
  changed_when: False


- block:

  - name: enable logging on Default trail in {{ trail_region }}
    command: >
      aws cloudtrail start-logging
                     --name Default
                     --region '{{ trail_region }}'
                     --profile '{{ aws_profile }}'

  - name: call optional notifier
    include: 'roles/{{ notifier_role }}/tasks/main.yml'
    vars:
      message: >
        enabled logging on the Default trail in
        <a href="{{ cloudtrail_url }}?region={{ trail_region }}">{{
          trail_region }} in account {{ aws_profile }}</a>
    when: notifier_role is defined

  when: '{{ not is_logging.stdout | bool }}'
