---
- name: setup cloudwatch event rule for {{ item.name }}
  cloudwatchevent_rule:
    name: "{{ item.name }}"
    event_pattern: "{{ item.event_pattern }}"
    description: "{{ item.description }}"
    profile: "{{ aws_profile }}"
    region: "{{ trail_region }}"
    targets:
    - id: "{{ item.target_id }}"
      arn: arn:aws:{{ item.target_type }}:{{ trail_region }}:{{ aws_account }}:{{ item.target_id }}
  with_items: "{{ cloudwatch_event_rules }}"
