---
- name: setup cloudwatch event rule for root logins
  cloudwatchevent_rule:
    name: RootLogin
    event_pattern: |-
      {
        "detail-type": [
          "AWS Console Sign In via CloudTrail"
        ],
        "detail": {
          "userIdentity": {
            "arn": [
              "Root"
            ]
          }
        }
      }
    description: Alert on any root logins to AWS account
    profile: "{{ aws_profile }}"
    region: "{{ trail_region }}"
    targets:
    - id: H3Help
      arn: arn:aws:sns:{{ trail_region }}:{{ aws_account }}:H3Help
