---

- name: disable CloudTrail in {{ trail_region }}
  cloudtrail:
    name: Default
    profile: '{{ aws_profile }}'
    region: '{{ trail_region }}'
    state: disabled
  register: _aws_cloudtrail

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      disabled CloudTrail in
      <a href="{{ _aws_cloudtrail_url }}?region={{ trail_region }}">{{
        trail_region }} in account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    _aws_cloudtrail is changed
