---

- name: set global facts
  set_fact:
    _aws_cloudtrail_url: https://console.aws.amazon.com/cloudtrail/home

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      started running role <b>aws-cloudtrail</b>
      on <a href="{{ _aws_cloudtrail_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined

- include_tasks: regions.yml

- include_tasks: activate.yml
  vars:
    trail_region: '{{ item }}'
  with_items: '{{ _aws_cloudtrail_active_regions }}'

- include_tasks: deactivate.yml
  vars:
    trail_region: '{{ item }}'
  with_items: '{{ _aws_cloudtrail_inactive_regions }}'

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      finished running role <b>aws-cloudtrail</b>
      on <a href="{{ _aws_cloudtrail_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined
