---

- include: roles/aws/tasks/regions.yml

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-cloudtrail</b>
      on <a href="{{ iam_url }}">account {{ profile }}</a>
  when: notifier_role is defined

- include: trail_default.yml
  vars:
    trail_region: '{{ item }}'
  with_items: regions

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-cloudtrail</b>
      on <a href="{{ iam_url }}">account {{ profile }}</a>
  when: notifier_role is defined
